# The original set of weights defined for the criticality score project using
# Rob Pike's algorithm as implemented in the original Python project.
algorithm: weighted_arithmetic_mean

inputs:
  - field: legacy.created_since
    weight: 1
    bounds:
      upper: 120
    distribution: zapfian

  - field: legacy.updated_since
    weight: 1
    bounds:
      upper: 120
      smaller_is_better: yes
    distribution: zapfian

  - field: legacy.contributor_count
    weight: 2
    bounds:
      upper: 5000
    distribution: zapfian

  - field: legacy.org_count
    weight: 1
    bounds:
      upper: 10
    distribution: zapfian

  - field: legacy.commit_frequency
    weight: 1
    bounds:
      upper: 1000
    distribution: zapfian

  - field: legacy.recent_release_count
    weight: 0.5
    bounds:
      upper: 26
    distribution: zapfian

  - field: legacy.updated_issues_count
    weight: 0.5
    bounds:
      upper: 5000
    distribution: zapfian

  - field: legacy.closed_issues_count
    weight: 0.5
    bounds:
      upper: 5000
    distribution: zapfian

  - field: legacy.issue_comment_frequency
    weight: 1
    bounds:
      upper: 15
    distribution: zapfian

  - field: legacy.github_mention_count
    weight: 2
    bounds:
      upper: 500000
    distribution: zapfian
