name: "Continuous Integration"

on:
  pull_request:

permissions: read-all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f
      with:
        go-version: 1.18
    - name: Run tests
      run: make test
  run-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
    - name: Run linter
      uses: github/super-linter@01d3218744765b55c3b5ffbb27e50961e50c33c5
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
