name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
          go-version: "1.21"
    - name: Run tests
      run: make test/unit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
      with:
          go-version: "1.21"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc
      with:
          args: --timeout=30m
  check-scorecard-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - name: Run tests
      run: make test/scorecard-version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
