name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  run-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
          go-version: "1.21"
    - name: Run tests
      run: make test/unit
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
      with:
          go-version: "1.21"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804
      with:
          args: --timeout=30m
  check-scorecard-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - name: Run tests
      run: make test/scorecard-version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
