name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        go-version: 1.19
    - name: Run tests
      run: make test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        go-version: 1.19
    - name: golangci-lint
      uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1
