name: OSSF Scorecard
on:
  push:
    # Only the default branch is supported.
    branches:
    - main
  schedule:
    # Weekly on Saturdays.
    - cron:  '30 1 * * 6'

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: "Checkout code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: "Run analysis"
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.0.0-alpha.2
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish the results for public repositories to enable scorecard badges. For more details, see
          # https://github.com/ossf/scorecard-action#publishing-results. 
          # For private repositories, `publish_results` will automatically be set to `false`, regardless 
          # of the value entered here.
          publish_results: true
      # https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      # Optional.
      - name: "Upload artifact"
        uses: actions/upload-artifact@1eb3cb2b3e0f29609092a73eb033bb759a334595 # v2
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      - name: "Upload SARIF results"
        uses: github/codeql-action/upload-sarif@96531062ba46eb11dee25758db76518ad30ee4cf # v1
        with:
          sarif_file: results.sarif
